scoreboard-title: "&3Hydra &8: &fSeason I"
scoreboard:
  - "&7&m--------------------"
  - "&3Rank:"
  - "&fDefault"
  - ""
  - "&3Online"
  - "&f%online%/%max%"
  - "%ifq%:"
  - "%ifq%:&3Queue &7(SG)"
  - "%ifq%:&f#4d5q"
  - ""
  - "&7servermc.net / sm3"
  - "&7&m--------------------"

scoreboard-pre-title: "&3Server &8: &3Ranked"
scoreboard-pre:
  - "&7&m--------------------"
  - "&fStatus&8: &a%status%"
  - "&fMap&8: &4%map%"
  - "&fStarting In&8: &c%timer%"
  - ""
  - "&7servermc.net / sm3"
  - "&7&m--------------------"

scoreboard-live-title: "&3Server &8: &3Ranked"
scoreboard-live:
  - "&7&m--------------------"
  - "&fStatus&8: &a%status%"
  - "&fSpectators&8: &4%spectators%"
  - "%ifg%:&fGrace Period&8: &c%timer%"
  - "%ifng%:&fTime Left&8: &c%timer%"
  - ""
  - "&7servermc.net / sm3"
  - "&7&m--------------------"