spawn: world,0,0,0,90,90

scoreboard-title: "&3Server &8: &fSeason I"
scoreboard:
  - "&7&m--------------------"
  - "&3Rank:"
  - "&fDefault"
  - ""
  - "&3Online"
  - "&f%online%/%max%"
  - "%ifq%:"
  - "%ifq%:&3Queue &7(SG)"
  - "%ifq%:&f#4d5q"
  - ""
  - "&7servermc.net / sm3"
  - "&7&m--------------------"

scoreboard-pre-title: "&3Server &8: &3Ranked"
scoreboard-pre:
  - "&7&m--------------------"
  - "&fStatus&8: &a%status%"
  - "&fMap&8: &4%map%"
  - "&fStarting In&8: &c%timer%"
  - ""
  - "&7servermc.net / sm3"
  - "&7&m--------------------"

scoreboard-live-title: "&3Server &8: &3Ranked"
scoreboard-live:
  - "&7&m--------------------"
  - "&fStatus&8: &a%status%"
  - "&fSpectators&8: &4%spectators%"
  - "%ifg%:&fGrace Period&8: &c%timer%"
  - "%ifng%:&fTimer&8: &c%timer%"
  - ""
  - "&7servermc.net / sm3"
  - "&7&m--------------------"

scoreboard-finished-title: "&3Server &8: &3Ranked"
scoreboard-finished:
  - "&7&m--------------------"
  - "&fWinner&8: &a%winner%"
  - ""
  - "&7servermc.net / sm3"
  - "&7&m--------------------"

players: 24

sounds:
  cooldown: "SUCCESSFUL_HIT"
  start: "SUCCESSFUL_HIT"

messages:
  map: "&6Map: &f%map%"
  starting-cooldown: "&6%timer% &7before the game starts."
  starting: "&eThe game has been started."
  dm-cooldown: "&6%timer% &7before the deathmatch starts."
  dm-starting: "&eThe deathmatch has been started."
  killed: "&c%dead% &7was killed by &c%killer%&7."
  dead: "&c%dead% &7died."
  discontinued: "&cSomeone left the game before starting. No stats has been changed."
  won: "&a%won% &7won against team &c%loss%&7."
  team:
    - "&c&lTeam 1"
    - "&4%player%&7: &7%damage% %elo_color%"